dist/manifest.json, src/background.js, src/content.js
Fixed: #9 and #10 
Implementation of "hide unsafe images" logic
Draft status 'cause I would like to dive into `background.js` and improve errors a little bit
=> Feature: hide unsafe images & performance

src/background.js, src/content.js
=> refactor: lazy loading

dist/manifest.json, package.json, src/background.js, src/content.js, src/utils.js
=> fix: handle dynamic js rendering #24

.eslintignore, .eslintrc.json, .github/workflows/integrate.yml, devModeCheck.sh, package-lock.json, package.json, src/background.js, src/content.js, src/utils.js
=> fix: add eslint

.eslintignore, .eslintrc.json, .github/workflows/integrate.yml, README.md, devModeCheck.sh, dist/manifest.json, package-lock.json, package.json, src/background.js, src/content.js, src/utils.js
@navendu-pottekkat Please test this PR
Changes:
=> v1.0.0 release

src/content.js
Fixed: #19 
Also probably fixed: #32 
@navendu-pottekkat Pls download and test this branch, I tested with `google images`, `4chan` and some `Ptubes` - works well for me
=> fix: loading lag

src/background/Model.ts, src/background/background.ts, src/content/DOMWatcher/DOMWatcher.ts, src/content/Filter/Filter.ts, src/content/Filter/ImageFilter.ts, src/content/Filter/VideoFilter.ts, src/content/content.ts, src/utils/Logger.ts, src/utils/Memory.ts, src/utils/types.ts
=> feat: div background & dom watcher & filter refact

src/background/Model.ts, src/content/DOMWatcher/DOMWatcher.ts, src/content/Filter/Filter.ts, src/content/Filter/ImageFilter.ts, src/content/Filter/VideoFilter.ts
Add request queue for prediction, tests show that time of filtering whole page decreased by 1-3 seconds :rocket: (especially for website with `lazy loading` logic)
Fixes #49
=> feat: add request queue

package-lock.json, package.json, src/background/Model.ts, src/background/background.ts
=> chore(deps): replace with temp nsfwjs

src/content/DOMWatcher/DOMWatcher.ts, src/content/Filter/ImageFilter.ts, src/content/Filter/VideoFilter.ts
Bug when image was not hidden in <body> tag
Fixes #60
=> Hide single img in body

package.json, src/background/Model.ts, src/content/DOMWatcher/DOMWatcher.ts, src/content/Filter/ImageFilter.ts, src/utils/LRUCache.ts
=> feat: add cache

.eslintignore, README.md, jest.config.js, package-lock.json, package.json, src/content/DOMWatcher/DOMWatcher.ts, test/e2e/singleNSFW.test.js, test/e2e/singleSFW.test.js, tsconfig.json
=> test: add e2e single img cases

src/popup/popup.html
@YegorZaremba I have made a simple design as a start. Please check it out
=> added basic popup

src/background/Model.ts, src/background/background.ts, src/content/Filter/Filter.ts
=> fix(model): add check for activeTabs

README.md, package-lock.json, package.json
Ease to start development in clean environment with one command.
i.e. ```npm run dev:chrome``` 
Fixes windows developers experience.
devDependencies:
web-ext
cross-env
npm-run-all
Fixes #107
- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] This change requires a documentation update
=> Use web-ext to run extension for development.

src/background/Prediction/PredictionQueue.ts
=> fix(worker): redundant set for filter effect

src/content/Filter/ImageFilter.ts
Related #114
`processing`, `sfw` and `nsfw`
=> feat(image-filter): add status attributes

.eslintignore, .eslintrc.json, .github/workflows/integrate.yml, jest-puppeteer.config.js, jest.config.js, jest.setup.js, package-lock.json, package.json, test/e2e/mutationNSFW.test.js, test/e2e/singleNSFW.test.js, test/e2e/singleSFW.test.js
e2e tests DDG search results
refactor single image tests
tests run sequentially  (otherwise there tons of performace issues).
CI tests enabled (takes time)
jest-puppeteer
Fixes # (issue)
tests
=> Test lazy loaded images filtering. Run tests in CI.

src/background/Model/Model.ts, src/popup/components/Production/index.tsx, tsconfig.json
=> feat(model): add filter strictness bar

src/content/DOMWatcher/DOMWatcher.ts, src/content/Filter/ImageFilter.ts, src/content/Filter/types.ts
=> fix(filter): rm redundant image type

src/background/Queue/ConcurrentQueue.ts, src/background/Queue/LoadingQueue.ts, src/background/Queue/PredictionQueue.ts
Not sure that its make filtering much faster, but load all images in first second is not great
=> fix(queue): add loading limits

src/content/DOMWatcher/DOMWatcher.ts, src/content/content.ts, test/e2e/mutationNSFW.test.js
=> fix(dom-watcher): add check for mutated divs

src/background/Model.ts, src/background/Queue/LoadingQueue.ts, src/background/Queue/PredictionQueue.ts, src/background/Queue/QueueBase.ts
=> fix(worker): improvements before v1.3.0

src/content/DOMWatcher/DOMWatcher.ts
Lets keep it simple
Related: #109 and #135
=> fix(dom-watcher): check images of target on every mutation

src/background/Queue/LoadingQueue.ts, src/background/Queue/PredictionQueue.ts, src/background/Queue/QueueBase.ts, src/background/Queue/QueueWrapper.ts, src/background/background.ts, src/content/DOMWatcher/DOMWatcher.ts, test/e2e/singleNSFW.test.js, test/e2e/singleSFW.test.js
=> feat(background): handle new users url in same tab and domain

dist/manifest.json, package-lock.json, package.json
=> chore: bump v1.3.0

src/background/Queue/LoadingQueue.ts
=> fix(queue): limitless loading (basically cache)

package-lock.json, src/popup/components/Footer/styles.ts, src/popup/components/Production/index.tsx, src/popup/index.tsx, webpack/webpack.common.js
=> chore: reduce popup size

dist/manifest.json, package-lock.json
=> fix(perm): remove declarativeContent

package-lock.json, package.json
=> chore(deps): bump tfjs

src/content/Filter/ImageFilter.ts, src/popup/components/Production/index.tsx, src/popup/redux/actions/settings/settingsActions.ts, src/popup/redux/reducers/settings.ts
- Grayscale filter is added for the style to show images
- Grayscale option is added to Filter effect select box
- `grayscale` lateral type is added for `filterEffect`
resolve #229
[![Image from Gyazo](https://i.gyazo.com/420c4961381f6e067105c8617590f327.png)](https://gyazo.com/420c4961381f6e067105c8617590f327)
[![Image from Gyazo](https://i.gyazo.com/a24371ee11488ce4757f6ecf99a948c0.jpg)](https://gyazo.com/a24371ee11488ce4757f6ecf99a948c0)
=> Feat/add Grayscale filter effect

.github/workflows/integrate.yml
Signed-off-by: Navendu Pottekkat <navendu@apache.org>
Try to fix CI.
=> fix: Puppeteer CI
